var data = {
    "year": "17-18",
    "degree_plans": [{
        "name": "Mechanical Engineering",
        "courses": [
            {
                "id": "ENGR111",
                "class" : "course",
                "full_name": "Foundations of Engineering I",
                "display_name" : "ENGR 111",
                "prereqs": [""],
                "coreqs": ["MATH151"],
                "prereqs_id" : "engr111p",
                "coreqs_id" : "engr111c",
                "hours": 2,
                "semester" : "semester10",
                "freshman_year" : true,
                "major_specific" : false,
                "core" : false,
                "description_title" : "Foundations of Engineering I",
                "description_header" : ["Credits 2. 1 Lecture Hour. 3 Lab Hours."],
                "description_body": "Introduction to the engineering profession, ethics, and disciplines; development of skills in teamwork, problem solving and design; other topics depending on the major include emphasis on computer applications and programming, visualization and CAD tools, introduction to electrical circuits, semiconductor devices, digital logic, communications and their application in systems; Newton's laws, unit conversions, statistics, computers, Excel; basic graphics skills; visualization and orthographic drawings.",
                "description_footer" : "Prerequisites: MATH 150 or MATH 151, or concurrent enrollment; admission to the College of Engineering."
            },
            {
                "id": "ENGR112",
                "class" : "course",
                "full_name": "Foundations of Engineering II",
                "display_name" : "ENGR 112",
                "prereqs": ["ENGR111"],
                "coreqs": [""],
                "prereqs_id" : "engr112p",
                "coreqs_id" : "engr112c",
                "hours": 2,
                "semester" : "semester20",
                "freshman_year" : true,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "Foundations of Engineering II",
                "description_header" : ["Credits 2. 1 Lecture Hour. 3 Lab Hours."],
                "description_body": "Continuation of ENGR 111. Topics include, depending on the major, emphasis on computer applications and programming and solids modeling using CAD tools or other software; fundamentals of engineering science; advanced graphic skills.",
                "description_footer" : "Prerequisite: ENGR 111; MATH 151 or concurrent enrollment; admission to the College of Engineering."
            },
            {
                "id": "MATH151",
                "class" : "course",
                "full_name": "Engineering Mathematics I",
                "display_name" : "MATH 151",
                "prereqs": ["MATH151"],
                "coreqs": ["MATH151"],
                "prereqs_id" : "math151p",
                "coreqs_id" : "math151c",
                "hours": 4,
                "semester" : "semester10",
                "freshman_year" : true,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "Engineering Mathematics I",
                "description_header" : ["Credits 4. 3 Lecture Hours. 2 Lab Hours."],
                "description_body": "Engineering Mathematics I. Rectangular coordinates, vectors, analytic geometry, functions, limits, derivatives of functions, applications, integration, computer algebra. MATH 171 designed to be a more demanding version of this course. No credit will be given for more than one of MATH 131, MATH 142, MATH 147, MATH 151 and MATH 171.",
                "description_footer" : "Prerequisite: MATH 150 or equivalent or acceptable score on TAMU Math Placement Exam."
            },
            {
                "id": "PHYS218",
                "class" : "course",
                "full_name": "Mechanics",
                "display_name" : "PHYS 218",
                "prereqs": [""],
                "coreqs": ["MATH151"],
                "prereqs_id" : "phys218p",
                "coreqs_id" : "phys218c",
                "hours": 4,
                "semester" : "semester10",
                "freshman_year" : true,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "Mechanics",
                "description_header" : ["Credits 4. 3 Lecture Hours. 3 Lab Hours."],
                "description_body": "Mechanics. Mechanics for students in science and engineering.",
                "description_footer" : "Prerequisite: MATH 151 or MATH 171 or registration therein."
            },
            {
                "id": "ENGL104",
                "class" : "course",
                "full_name": "Composition and Rhetoric",
                "display_name" : "ENGL 104",
                "prereqs": [""],
                "coreqs": [""],
                "prereqs_id" : "engl104p",
                "coreqs_id" : "engl104c",
                "hours": 3,
                "semester" : "semester10",
                "freshman_year" : true,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "Composition and Rhetoric",
                "description_header" : ["Credits 3. 3 Lecture Hours."],
                "description_body": "Composition and Rhetoric. Focus on referential and persuasive researched essays through the development of analytical reading ability, critical thinking and library research skills; for freshman and sophomore students only.",
                "description_footer" : ""
            },
            {
                "id": "UCC1",
                "class" : "course",
                "full_name": "University Core Curriculum",
                "display_name" : "UCC Elective",
                "prereqs": [""],
                "coreqs": [""],
                "prereqs_id" : "ucc1p",
                "coreqs_id" : "ucc1c",
                "hours": 3,
                "semester" : "semester10",
                "freshman_year" : false,
                "major_specific" : false,
                "core_course" : true,
                "description_title" : "University Core Curriculum",
                "description_header" : ["POLS 206, 207","6 credits of American History","3 credits of Creative Arts","3 credits of Social/Behavoiral Sciences"],
                "description_body": "6 credits of International, Cultural Diversity (ICD) must be taken and can be fulfilled by these UCC electives",
                "description_footer" : "core.tamu.edu"
            },
            {
                "id": "MATH152",
                "class" : "course",
                "full_name": "Engineering Mathematics II",
                "display_name" : "MATH 152",
                "prereqs": ["MATH151"],
                "coreqs": [""],
                "prereqs_id" : "math152p",
                "coreqs_id" : "math152c",
                "hours": 4,
                "semester" : "semester20",
                "freshman_year" : true,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "Engineering Mathematics II",
                "description_header" : ["Credits 4. 3 Lecture Hours. 2 Lab Hours."],
                "description_body": "Engineering Mathematics II. Differentiation and integration techniques and their applications (area, volumes, work), improper integrals, approximate integration, analytic geometry, vectors, infinite series, power series, Taylor series, computer algebra. MATH 172 designed to be a more demanding version of this course. No credit will be given for more than one of MATH 148, MATH 152 and MATH 172. ",
                "description_footer" : "Prerequisite: MATH 151 or equivalent."
            },
            {
                "id": "PHYS208",
                "class" : "course",
                "full_name": "Electricity and Optics",
                "display_name" : "PHYS 208",
                "prereqs": ["PHYS218"],
                "coreqs": ["MATH152"],
                "prereqs_id" : "phys208p",
                "coreqs_id" : "phys208c",
                "hours": 4,
                "semester" : "semester20",
                "freshman_year" : true,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "Electricity and Optics",
                "description_header" : ["Credits 4. 3 Lecture Hours. 3 Lab Hours."],
                "description_body": "Electricity and Optics. Continuation of PHYS 218. Electricity, magnetism, and introduction to optics. Primarily for students in science and engineering.",
                "description_footer" : "Prerequisites: PHYS 218; MATH 152 or MATH 172 or registration therein."
            },
            {
                "id": "CHEM107",
                "class" : "course",
                "full_name": "Gen. Chem. for Engineers/Lab",
                "display_name" : "CHEM 107/117",
                "prereqs": [""],
                "coreqs": [""],
                "prereqs_id" : "chem107p",
                "coreqs_id" : "chem107c",
                "hours": 4,
                "semester" : "semester20",
                "freshman_year" : true,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "General chemistry for Engineers/Lab",
                "description_header" : ["Credits 4. 3 Lecture Hours. 1 Lab Hours."],
                "description_body": "Introduction to important concepts and principles of chemistry; emphasis on areas considered most relevant in an engineering context; practical applications of chemical principles in engineering and technology. Students completing CHEM 107 and changing majors to curricula requiring CHEM 101 and CHEM 102 may substitute CHEM 107 for CHEM 101. Students may not receive credit for both CHEM 107 and CHEM 101.",
                "description_footer" : "Prerequisite: Concurrent enrollment in CHEM 117."
            },
            {
                "id": "UCC2",
                "class" : "course",
                "full_name": "University Core Curriculum",
                "display_name" : "UCC Elective",
                "prereqs": [""],
                "coreqs": [""],
                "prereqs_id" : "ucc2p",
                "coreqs_id" : "ucc2c",
                "hours": 3,
                "semester" : "semester20",
                "freshman_year" : false,
                "major_specific" : false,
                "core_course" : true,
                "description_title" : "University Core Curriculum",
                "description_header" : ["POLS 206, 207","6 credits of American History","3 credits of Creative Arts","3 credits of Social/Behavoiral Sciences"],
                "description_body": "6 credits of International, Cultural Diversity (ICD) must be taken and can be fulfilled by these UCC electives",
                "description_footer" : "core.tamu.edu"
            },
            {
                "id": "MATH251",
                "class" : "course",
                "full_name": "Engineering Mathematics III",
                "display_name" : "MATH 251",
                "prereqs": ["MATH152"],
                "coreqs": [""],
                "prereqs_id" : "math251p",
                "coreqs_id" : "math251c",
                "hours": 3,
                "semester" : "semester30",
                "freshman_year" : false,
                "major_specific" : false,
                "core_course" : false,
                "description_title" : "MATH 251 Engineering Mathematics III",
                "description_header" : ["Credits 3. 3 Lecture Hours."],
                "description_body": "Vector algebra, calculus of functions of several variables, partial derivatives, directional derivatives, gradient, multiple integration, line and surface integrals, Green's and Stokes' theorems. MATH 221 designed to be a more demanding version of this course. No credit will be given for more than one of MATH 221, MATH 251 and MATH 253.",
                "description_footer" : "Prerequisite: MATH 148, MATH 152, or MATH 172."
            }
        ]
    }]
}
